#########################################################################
#  _____  _                       _                             _       #
# |  __ \(_)                     | |                           | |      #
# | |  | |_ ___  ___ ___  _ __ __| |         __ _  __ _ _ __ __| | __ _ #
# | |  | | / __|/ __/ _ \| '__/ _` |        / _` |/ _` | '__/ _` |/ _` |#
# | |__| | \__ \ (_| (_) | | | (_| |       | (_| | (_| | | | (_| | (_| |#
# |_____/|_|___/\___\___/|_|  \__,_|        \__,_|\__,_|_|  \__,_|\__,_|#
#                                       ______                          #
#                                      |______|                         #
#########################################################################
bot:
  token: ''
  id: ''
guild:
  id: ''
settings:
  roles:
    officers: ['', '']
  channels:
    log: ''
